{
 "title": "Ballerina Prometheus Metrics",
 "description": "Monitor Ballerina HTTP/HTTPs Services, HTTP Clients and SQL Clients",
 "tags": [
  "ballerina",
  "http",
  "sql"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(requests_total_value, instance)"
   },
   {
    "name": "entrypoint_function_module",
    "label": "entrypoint-function-module",
    "query": "label_values(requests_total_value, entrypoint_function_module)"
   },
   {
    "name": "entrypoint_function_position",
    "label": "entrypoint-function-position",
    "query": "label_values(requests_total_value, entrypoint_function_position)"
   },
   {
    "name": "protocol",
    "label": "protocol",
    "query": "label_values(requests_total_value, protocol)"
   },
   {
    "name": "http_method",
    "label": "http-method",
    "query": "label_values(requests_total_value, http_method)"
   },
   {
    "name": "http_url",
    "label": "http-url",
    "query": "label_values(requests_total_value, http_url)"
   },
   {
    "name": "src_object_name",
    "label": "src-object-name",
    "query": "label_values(requests_total_value, src_object_name)"
   },
   {
    "name": "src_function_name",
    "label": "src-function-name",
    "query": "label_values(requests_total_value, src_function_name)"
   },
   {
    "name": "db_action",
    "label": "db-action",
    "query": "label_values(requests_total_value{src_object_name=\"ballerinax/mysql/Client\"}, src_function_name)"
   },
   {
    "name": "http_status_code_group",
    "label": "http-status-code-group",
    "query": "label_values(requests_total_value, http_status_code_group)"
   },
   { "name": "peer_address", "label": "peer-address", "query": "label_values(peer_address)" }
  ]
 },
 "panels": [
  {
   "title": "Ballerina Up / Down",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "up{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Live Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"ballerina-services\"} | json | level=\"ERROR\""
    }
   ]
  },
  {
   "title": "Where are the errors?",
   "type": "table",
   "description": "increase(...[1h]): Calculates the total increase of a counter over the last hour. sum(...) by (...): This aggregates the counts and groups them by the labels.",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(increase(response_errors_total_value[1h])) by (entrypoint_service_name, http_url, http_method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ballerina HTTP Service Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests / min",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(max_over_time(requests_total_value{instance=~\"$instance\",protocol=~\"$protocol\",http_method=~\"$http_method\",http_url=~\"$http_url\",entrypoint_function_module=~\"$entrypoint_function_module\",entrypoint_function_position=~\"$entrypoint_function_position\",src_object_name=~\"$src_object_name\"}[1m])-min_over_time(requests_total_value{instance=~\"$instance\",protocol=~\"$protocol\",http_method=~\"$http_method\",http_url=~\"$http_url\",entrypoint_function_module=~\"$entrypoint_function_module\",entrypoint_function_position=~\"$entrypoint_function_position\",src_object_name=~\"$src_object_name\"}[1m]))"
      }
     ]
    },
    {
     "title": "Errors /  min",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((sum(max_over_time(requests_total_value{instance=~\"$instance\",src_object_name=\"ballerina/http/Caller\",http_status_code_group=\"4xx\"}[1m])-min_over_time(requests_total_value{instance=~\"$instance\",src_object_name=\"ballerina/http/Caller\",http_status_code_group=\"4xx\"}[1m]))) OR vector(0))+((sum(max_over_time(requests_total_value{instance=~\"$instance\",src_object_name=\"ballerina/http/Caller\",http_status_code_group=\"5xx\"}[1m])-min_over_time(requests_total_value{instance=~\"$instance\",src_object_name=\"ballerina/http/Caller\",http_status_code_group=\"5xx\"}[1m]))) OR vector(0))"
      }
     ]
    },
    {
     "title": "Inprogress Requests",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(inprogress_requests_value{instance=~\"$instance\",entrypoint_function_module=~\"$entrypoint_function_module\",entrypoint_function_position=~\"$entrypoint_function_position\",src_object_name=~\"$src_object_name\"})"
      }
     ]
    },
    {
     "title": "Error %",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((sum(max_over_time(requests_total_value{instance=~\"$instance\",src_object_name=\"ballerina/http/Caller\",http_status_code_group=\"4xx\"}[1m])\n-\n  min_over_time(requests_total_value{instance=~\"$instance\",src_object_name=\"ballerina/http/Caller\",http_status_code_group=\"4xx\"}[1m])) OR vector(0))\n+\n(sum(max_over_time(requests_total_value{instance=~\"$instance\",src_object_name=\"ballerina/http/Caller\",http_status_code_group=\"5xx\"}[1m]) \n-    min_over_time(requests_total_value{instance=~\"$instance\",src_object_name=\"ballerina/http/Caller\",http_status_code_group=\"5xx\"}[1m])) OR vector(0)))\n*100\n/\nsum(max_over_time(requests_total_value{instance=~\"$instance\",src_object_name=\"ballerina/http/Caller\"}[1m]) - min_over_time(requests_total_value{instance=~\"$instance\",src_object_name=\"ballerina/http/Caller\"}[1m]))\n"
      }
     ]
    },
    {
     "title": "Throughput",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum without (http_status_code_group)(rate(requests_total_value{instance=~\"$instance\",entrypoint_function_module=~\"$entrypoint_function_module\",entrypoint_function_position=~\"$entrypoint_function_position\",src_object_name=\"ballerina/http/Caller\"}[1m]))",
       "legendFormat": "Instance: {{instance}}, Source Object Name: {{src_object_name}}, Source Function Name: {{src_function_name}}"
      }
     ]
    },
    {
     "title": "Response Time Percentiles",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "response_time_seconds{instance=~\"$instance\",protocol=~\"$protocol\",http_method=~\"$http_method\",http_url=~\"$http_url\",entrypoint_function_module=~\"$entrypoint_function_module\",entrypoint_function_position=~\"$entrypoint_function_position\"}",
       "legendFormat": "Instance: {{instance}}, Protocol: {{protocol}}, Method: {{http_method}}, URL: {{http_url}}, Quantile: {{quantile}}"
      }
     ]
    },
    {
     "title": "HTTP Status Codes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 149 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(requests_total_value{instance=~\"$instance\", src_function_name=\"respond\",src_object_name=\"ballerina/http/Caller\",http_status_code_group=\"1xx\"}[1m])",
       "legendFormat": "1xx Informational responses - Instance: {{instance}}"
      },
      {
       "expr": "rate(requests_total_value{instance=~\"$instance\", src_function_name=\"respond\",src_object_name=\"ballerina/http/Caller\",http_status_code_group=\"2xx\"}[1m])",
       "legendFormat": "2xx Successful responses - Instance: {{instance}}"
      },
      {
       "expr": "rate(requests_total_value{instance=~\"$instance\", src_function_name=\"respond\",src_object_name=\"ballerina/http/Caller\",http_status_code_group=\"3xx\"}[1m])",
       "legendFormat": "3xx Redirections - Instance: {{instance}}"
      },
      {
       "expr": "rate(requests_total_value{instance=~\"$instance\", src_function_name=\"respond\",src_object_name=\"ballerina/http/Caller\",http_status_code_group=\"4xx\"}[1m])",
       "legendFormat": "4xx Client errors - Instance: {{instance}}"
      },
      {
       "expr": "rate(requests_total_value{instance=~\"$instance\", src_function_name=\"respond\",src_object_name=\"ballerina/http/Caller\",http_status_code_group=\"5xx\"}[1m])",
       "legendFormat": "5xx Server errors - Instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Top 5 services",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 149 },
     "targets": [
      {
       "expr": "topk(5,requests_total_value{src_service_resource=\"true\"})",
       "legendFormat": "Instance: {{instance}}, Protocol: {{protocol}}, Method: {{http_method}}, URL: {{http_url}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Ballerina HTTP Client Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests / min",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum( max_over_time(requests_total_value{src_object_name=\"ballerina/http/HttpClient\",instance=~\"$instance\", peer_address=~\"$peer_address\",src_function_name=~\"$src_function_name\"}[1m]) - min_over_time(requests_total_value{src_object_name=\"ballerina/http/HttpClient\",instance=~\"$instance\", peer_address=~\"$peer_address\",src_function_name=~\"$src_function_name\"}[1m]) )"
      }
     ]
    },
    {
     "title": "Errors /  min",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((sum( max_over_time(requests_total_value{ instance=~\"$instance\", src_function_name=~\"$src_function_name\",http_status_code_group=\"4xx\",src_object_name=\"ballerina/http/HttpClient\"}[1m]) - min_over_time(requests_total_value{ instance=~\"$instance\", src_function_name=~\"$src_function_name\",http_status_code_group=\"4xx\",src_object_name=\"ballerina/http/HttpClient\"}[1m]))) OR vector(0)) + ((sum(max_over_time(requests_total_value{ instance=~\"$instance\", src_function_name=~\"$src_function_name\",http_status_code_group=\"5xx\",src_object_name=\"ballerina/http/HttpClient\"}[1m]) - min_over_time(requests_total_value{instance=~\"$instance\", src_function_name=~\"$src_function_name\",http_status_code_group=\"5xx\",src_object_name=\"ballerina/http/HttpClient\"}[1m]))) OR vector(0))"
      }
     ]
    },
    {
     "title": "Inprogress Requests",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(inprogress_requests_value{src_object_name=\"ballerina/http/HttpClient\",instance=~\"$instance\"})"
      }
     ]
    },
    {
     "title": "Error %",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((sum( max_over_time({__name__=~\"requests_total_value\", instance=~\"$instance\", src_function_name=~\"$src_function_name\",src_object_name=\"ballerina/http/HttpClient\",http_status_code_group=\"4xx\"}[1m]) - min_over_time({__name__=~\"requests_total_value\", instance=~\"$instance\", src_function_name=~\"$src_function_name\",src_object_name=\"ballerina/http/HttpClient\",http_status_code_group=\"4xx\"}[1m])) OR vector(0)) + ((sum(max_over_time({__name__=~\"requests_total_value\", instance=~\"$instance\", src_function_name=~\"$src_function_name\",src_object_name=\"ballerina/http/HttpClient\",http_status_code_group=\"5xx\"}[1m]) - min_over_time({__name__=~\"requests_total_value\", instance=~\"$instance\", src_function_name=~\"$src_function_name\",src_object_name=\"ballerina/http/HttpClient\",http_status_code_group=\"5xx\"}[1m])) OR  vector(0) )))*100 / sum( max_over_time({__name__=~\"requests_total_value\", instance=~\"$instance\", src_function_name=~\"$src_function_name\",src_object_name=\"ballerina/http/HttpClient\"}[1m]) - min_over_time({__name__=~\"requests_total_value\", instance=~\"$instance\", src_function_name=~\"$src_function_name\",src_object_name=\"ballerina/http/HttpClient\"}[1m]))\n"
      }
     ]
    },
    {
     "title": "Throughput",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 122 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum without (http_status_code_group) (rate(requests_total_value{instance=~\"$instance\",peer_address=~\"$peer_address\",src_object_name=\"ballerina/http/HttpClient\"}[1m]))",
       "legendFormat": "Instance: {{instance}}, Method: {{http_method}}, Peer Address: {{peer_address}}, Service Name: {{entrypoint_service_name}}"
      }
     ]
    },
    {
     "title": "Response Time Percentiles",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 122 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "response_time_seconds{instance=~\"$instance\",peer_address=~\"$peer_address\",src_object_name=\"ballerina/http/HttpClient\"}",
       "legendFormat": "Instance: {{instance}}, Method: {{http_method}}, Peer Address: {{peer_address}}, Service Name: {{entrypoint_service_name}}"
      }
     ]
    },
    {
     "title": "HTTP Status Codes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate({__name__=~\"requests_total_value\", instance=~\"$instance\", src_function_name=~\"$src_function_name\",src_object_name=\"ballerina/http/HttpClient\",http_status_code_group=\"1xx\"}[1m])",
       "legendFormat": "1xx Informational responses - Instance: {{instance}}, Peer Address: {{peer_address}}"
      },
      {
       "expr": "rate({__name__=~\"requests_total_value\", instance=~\"$instance\", src_function_name=~\"$src_function_name\",src_object_name=\"ballerina/http/HttpClient\",http_status_code_group=\"2xx\"}[1m])",
       "legendFormat": "2xx Successful responses - Instance: {{instance}}, Peer Address: {{peer_address}}"
      },
      {
       "expr": "rate({__name__=~\"requests_total_value\", instance=~\"$instance\", src_function_name=~\"$src_function_name\",src_object_name=\"ballerina/http/HttpClient\",http_status_code_group=\"3xx\"}[1m])",
       "legendFormat": "3xx Redirections - Instance: {{instance}}, Peer Address: {{peer_address}}"
      },
      {
       "expr": "rate({__name__=~\"requests_total_value\", instance=~\"$instance\", src_function_name=~\"$src_function_name\",src_object_name=\"ballerina/http/HttpClient\",http_status_code_group=\"4xx\"}[1m])",
       "legendFormat": "4xx Client errors - Instance: {{instance}}, Peer Address: {{peer_address}}"
      },
      {
       "expr": "rate({__name__=~\"requests_total_value\", instance=~\"$instance\", src_function_name=~\"$src_function_name\",src_object_name=\"ballerina/http/HttpClient\",http_status_code_group=\"5xx\"}[1m])",
       "legendFormat": "5xx Server errors - Instance: {{instance}}, Peer Address: {{peer_address}}"
      }
     ]
    },
    {
     "title": "Top 5 remote services",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 131 },
     "targets": [
      {
       "expr": "topk(5,requests_total_value{src_object_name=\"ballerina/http/HttpClient\"})",
       "legendFormat": "Instance: {{instance}}, Action: {{action}}, Method: {{http_method}}, Peer Address: {{peer_address}}, URL: {{http_url}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Ballerina SQL Client Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Executions / min",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(max_over_time(requests_total_value{instance=~\"$instance\",src_function_name=~\"$db_action\",src_object_name=\"ballerinax/mysql/Client\"}[1m])-min_over_time(requests_total_value{instance=~\"$instance\",src_function_name=~\"$db_action\",src_object_name=\"ballerinax/mysql/Client\"}[1m]))"
      }
     ]
    },
    {
     "title": "Errors /  min",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (max_over_time(requests_total_value{instance=~\"$instance\",src_function_name=~\"$db_action\",src_object_name=\"ballerinax/mysql/Client\",error=\"true\"}[1m]) - min_over_time(requests_total_value{instance=~\"$instance\",src_function_name=~\"$db_action\",src_object_name=\"ballerinax/mysql/Client\",error=\"true\"}[1m])) OR  vector(0)"
      }
     ]
    },
    {
     "title": "Inprogress Statements",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(inprogress_requests_value{src_function_name=~\"$db_action\",src_object_name=\"ballerinax/mysql/Client\"})"
      }
     ]
    },
    {
     "title": "Error %",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (max_over_time(requests_total_value{instance=~\"$instance\",src_function_name=~\"$db_action\",src_object_name=\"ballerinax/mysql/Client\",error=\"true\"}[1m]) - min_over_time(requests_total_value{instance=~\"$instance\",src_function_name=~\"$db_action\",src_object_name=\"ballerinax/mysql/Client\",error=\"true\"}[1m]))*100/sum(max_over_time(requests_total_value{instance=~\"$instance\",src_function_name=~\"$db_action\",src_object_name=\"ballerinax/mysql/Client\"}[1m]) - min_over_time(requests_total_value{instance=~\"$instance\",src_function_name=~\"$db_action\",src_object_name=\"ballerinax/mysql/Client\"}[1m]))"
      }
     ]
    },
    {
     "title": "Ballerina SQL Throughput",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 123 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(requests_total_value{instance=~\"$instance\",src_function_name=~\"$db_action\",src_object_name=\"ballerinax/mysql/Client\"}[1m])",
       "legendFormat": "Instance: {{instance}}, Service Name: {{entrypoint_service_name}}, Function Name: {{entrypoint_function_name}}"
      }
     ]
    },
    {
     "title": "Ballerina SQL Response Time Percentiles",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 123 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "response_time_seconds{instance=~\"$instance\",src_function_name=~\"$db_action\",src_object_name=\"ballerinax/mysql/Client\"}",
       "legendFormat": "Instance: {{instance}}, Quantile: {{quantile}}, Time Window: {{timeWindow}}, Service Name: {{entrypoint_service_name}}, Function Name: {{entrypoint_function_name}}"
      }
     ]
    },
    {
     "title": "Ballerina SQL Errors",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 132 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(requests_total_value{instance=~\"$instance\",src_function_name=~\"$db_action\",src_object_name=\"ballerinax/mysql/Client\",error=\"true\"}[1m]) OR  vector(0)",
       "legendFormat": "Instance: {{instance}}, Service Name: {{entrypoint_service_name}}, Function Name: {{entrypoint_function_name}}"
      }
     ]
    },
    {
     "title": "Top 5 SQL actions",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 132 },
     "targets": [
      {
       "expr": "topk(5,requests_total_value{src_function_name=~\"$src_function_name\",src_object_name=\"ballerinax/mysql/Client\"})",
       "legendFormat": "Instance: {{instance}}, Service Name: {{entrypoint_service_name}}, Function Name: {{entrypoint_function_name}}"
      }
     ]
    }
   ]
  }
 ]
}